version: '2'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
  jenkins:
    image: jenkins
    ports:
      - "8080:8080"
    volumes:
      - data:/var/jenkins_home

volumes:
  data: {}
