FROM       clojure:lein-2.6.1
MAINTAINER aaarnett@gmail.com

# Update apt-get sources AND install MongoDB
#RUN apt-get update && apt-get install -y 

# Create the MongoDB data directory
#RUN mkdir -p /data/db

# Expose port #27017 from the container to the host
#EXPOSE 27017

# Set /usr/bin/mongod as the dockerized entry-point application
#ENTRYPOINT ["/usr/bin/mongod"]
